# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 089e5b3b7eb7b4fca7176a5cd730f443f0c370dbc33ae179448734f48759bcfcc47228d1fdffa190376a839659b176516a8046115510706428054490acb82235

test:
  secret_key_base: 9f1c1bbdeaacc674f113fabba8bfc8ec38623115822494f2c9c04c6412f3aef0c941f5ba8260733b106a4930ea42981e9050c7d29816ac8008f32d30e915cc3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
