# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a153cb6f10a6c3bd684da813e2bb7cfb671f036267e62314b19183d27374f85503d1568b41e7d8aab10917304653039b4a93268b1e8b3c4b24637fb41fc0ece

test:
  secret_key_base: ae6e442715a8ef1b811ea1948ba8bf7261e7dde33f61a5eb745cbe07f9dcb167d7e8856af883a8f8a223fd33b1419f2221fe29347e6b6f19b8e3a59bdb2518c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
