# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9dd261eca2c6c7ace55a202c477268df49634be77e520655f63de3235ca87d55975c3981681adb6dc92676136805ba3f64d69ec651a37351bc8d8a2e7bfa616e

test:
  secret_key_base: 30d44bf29e3d609060e3df98d2e6a4a7cef8a86b172ccc1a99c075f649d0d93f0a22f6b38176da1bfd81ec5b8fa239edf0551f862c30ad25cbf738173c08b03f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
