# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16c29378779dfac8b5edf0e9a874e2a8ce30affe7224da64589c390e17300e40043b25b6811f9bbd795b099933c6fd41c51725290b62394b9744606f2472b81b

test:
  secret_key_base: 6630bd5154bf0365b15bd64a73dcfa2d49b158db108754b8e2cb4673f946a208ab5090bab76bc1b58cba9396fee9edc4abff08be11c6e952b1c83178c9c5448e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
